#!/bin/bash
mkdir -p ~/.local/share/applications
mkdir -p ~/.local/share/tubian
mkdir -p "$HOME"/Tubian
mkdir -p "$HOME"/.cache

cp -fa "$0".data/wine-7.18 "$HOME"/Tubian
cp -fa "$0".data/cache/winetricks  "$HOME"/.cache

cat >~/.local/share/tubian/ie8 <<EOF
#!/bin/bash
export WINEPREFIX="$HOME"/Tubian/IE8 
~/Tubian/wine-7.18/bin/wine start /unix ~/Tubian/IE8/'drive_c/Program Files/Internet Explorer/iexplore.exe' 
EOF

chmod 755 ~/.local/share/tubian/ie8

cat >~/.local/share/applications/IE8.desktop <<EOF
[Desktop Entry] 
Type=Application 
Name=IE8
Exec=~/.local/share/tubian/ie8
Categories=Network;
EOF

kbuildsycoca5

export WINEPREFIX="$HOME"/Tubian/IE8
export WINEARCH=win32
export WINE="$HOME"/Tubian/wine-7.18/bin/wine
"$0".data/winetricks  ie8  fakechinese corefonts ie8_kb2936068


