#!/bin/bash
mkdir -p ~/.local/share/applications
mkdir -p ~/.local/share/tubian
mkdir -p "$HOME"/Tubian
mkdir -p "$HOME"/.cache

cp -fa "$0".data/wine-7.18 "$HOME"/Tubian
cp -fa "$0".data/cache/winetricks  "$HOME"/.cache

cat >~/.local/share/tubian/Thunder <<EOF
#!/bin/bash
export WINEPREFIX="$HOME"/Tubian/Thunder 
~/Tubian/wine-7.18/bin/wine start /unix ~/Tubian/Thunder/drive_c/'Program Files'/'Thunder Network'/MiniThunder/Bin/ThunderMini.exe 
EOF

chmod 755 ~/.local/share/tubian/Thunder

cat >~/.local/share/applications/Thunder.desktop <<EOF
[Desktop Entry] 
Type=Application 
Name=迅雷
Exec=~/.local/share/tubian/Thunder
Categories=Network;
EOF

kbuildsycoca5

export WINEPREFIX="$HOME"/Tubian/Thunder
export WINEARCH=win32
export WINE="$HOME"/Tubian/wine-7.18/bin/wine
"$0".data/winetricks    fakechinese corefonts 
rm -f "$HOME"/Tubian/Thunder/drive_c/windows/system32/winemenubuilder.exe 
~/Tubian/wine-7.18/bin/wine start /unix "$0".data/setup.exe


