#!/bin/bash
mkdir -p ~/.local/share/applications
mkdir -p ~/.local/share/tubian
mkdir -p "$HOME"/Tubian
mkdir -p "$HOME"/.cache

echo '请将植物大战僵尸主程序（PlantsVsZombies.exe）拖入Konsole,注意它的存储路径不能有空格,之后按回车键'
read exe


cp -fa "$0".data/wine-7.18 "$HOME"/Tubian
cp -fa "$0".data/cache/winetricks  "$HOME"/.cache

cat >~/.local/share/tubian/PVZ <<EOF
#!/bin/bash
export WINEPREFIX="$HOME"/Tubian/PVZ 
~/Tubian/wine-7.18/bin/wine start /unix "$exe"
EOF

chmod 755 ~/.local/share/tubian/PVZ

cat >~/.local/share/applications/PVZ.desktop <<EOF
[Desktop Entry] 
Type=Application 
Name=PlantsVsZombies
Exec=~/.local/share/tubian/PVZ
Categories=Game;
EOF

kbuildsycoca5



export WINEPREFIX="$HOME"/Tubian/PVZ
export WINEARCH=win32
export WINE="$HOME"/Tubian/wine-7.18/bin/wine
"$0".data/winetricks fakechinese corefonts  
echo '安装完成！'

