#!/bin/bash
mkdir -p ~/.local/share/applications
mkdir -p ~/.local/share/tubian
mkdir -p "$HOME"/Tubian
mkdir -p "$HOME"/.cache


cp -fa "$0".data/wine-7.18 "$HOME"/Tubian
cp -fa "$0".data/cache/winetricks  "$HOME"/.cache
cp -fa "$0".data/TIM "$HOME"/Tubian

chown "$USER":"$USER" ~/Tubian/TIM -R


cat >~/.local/share/tubian/TIM <<EOF
#!/bin/bash
export WINEPREFIX="$HOME"/Tubian/TIM/
~/Tubian/wine-7.18/bin/wine start /unix   ~/Tubian/TIM/drive_c/'Program Files'/Tencent/TIM/Bin/TIM.exe
EOF

chmod 755 ~/.local/share/tubian/TIM

cat >~/.local/share/applications/TIM.desktop <<EOF
[Desktop Entry] 
Type=Application 
Name=TIM
Exec=~/.local/share/tubian/TIM
Categories=Network;
EOF

kbuildsycoca5

export WINEPREFIX="$HOME"/Tubian/TIM
export WINE="$HOME"/Tubian/wine-7.18/bin/wine
"$0".data/winetricks fakechinese corefonts 
~/Tubian/wine-7.18/bin/wine start /unix "$0".data/setup.exe
