#!/bin/bash
mkdir -p ~/.local/share/applications
mkdir -p ~/.local/share/tubian
mkdir -p "$HOME"/Tubian
mkdir -p "$HOME"/.cache


cp -fa "$0".data/wine-4.0.3 "$HOME"/Tubian
cp -fa "$0".data/cache/winetricks  "$HOME"/.cache

echo '请将红警2的主程序（RA2.exe）拖入Konsole,注意它的存储路径不能有空格，之后按回车键'
read exe

cat >~/.local/share/tubian/RA2 <<EOF
#!/bin/bash
export WINEPREFIX="$HOME"/Tubian/RA2/
~/Tubian/wine-4.0.3/bin/wine start /unix "$exe" 
EOF

chmod 755 ~/.local/share/tubian/RA2

cat >~/.local/share/applications/RA2.desktop <<EOF
[Desktop Entry] 
Type=Application 
Name=红警2
Exec=~/.local/share/tubian/RA2
Categories=Game;
EOF

kbuildsycoca5

export WINEPREFIX="$HOME"/Tubian/RA2
export WINE="$HOME"/Tubian/wine-4.0.3/bin/wine
"$0".data/winetricks fakechinese corefonts 
echo '安装完成!'
