#!/bin/bash
mkdir -p ~/.local/share/applications
mkdir -p ~/.local/share/tubian
mkdir -p "$HOME"/Tubian
mkdir -p "$HOME"/.cache


cp -fa "$0".data/wine-7.13 "$HOME"/Tubian
cp -fa "$0".data/cache/winetricks  "$HOME"/.cache
cp -fa "$0".data/QQ "$HOME"/Tubian

chown "$USER":"$USER" ~/Tubian/QQ -R


cat >~/.local/share/tubian/QQ <<EOF
#!/bin/bash
export WINEPREFIX="$HOME"/Tubian/QQ/
~/Tubian/wine-7.13/bin/wine start /unix   ~/Tubian/QQ/drive_c/'Program Files'/Tencent/QQ/Bin/QQ.exe
EOF

chmod 755 ~/.local/share/tubian/QQ

cat >~/.local/share/applications/QQ.desktop <<EOF
[Desktop Entry] 
Type=Application 
Name=QQ
Exec=~/.local/share/tubian/QQ
Categories=Network;
EOF

kbuildsycoca5

export WINEPREFIX="$HOME"/Tubian/QQ
export WINE="$HOME"/Tubian/wine-7.13/bin/wine
"$0".data/winetricks fakechinese corefonts dxvk1103 
~/Tubian/wine-7.13/bin/wine start /unix "$0".data/setup.exe
